### ISSUE TITLE
Add experimental protocol

### ISSUE THREAD

**Issue by nikosft** [multiformats/multiaddr#113]
I propose to reserve an identifier for "experimental" protocols. Generally this option will be ignored (even dropped in public networks) but it can be used to facilitate implementers experimenting with new protocols, or with add-on to existing ones.

**Comment by Stebalien** [comment]
Protocols are just multicodecs so you should be able to use any multicodec in the ["private use area"](https://github.com/multiformats/multicodec/#private-use-area). Just be careful not to come to _rely_ on this protocol code, because it will _never_ be stabilized.

If you're planning on deploying your code at all, I recommend allocating a ["draft"](https://github.com/multiformats/multicodec/#status) multicodec.

(closing for tracking, leave a comment if this doesn't solve your issue and I'll reopen).
