### ISSUE TITLE
/dns in multiaddrs

### ISSUE THREAD

**Issue by jbenet** [multiformats/multiaddr#22]
There's been some conversation on how to handle DNS, in these issues and others:
- https://github.com/multiformats/go-multiaddr/issues/7
- https://github.com/multiformats/go-multiaddr/pull/26

Finally looking back at this-- sorry for the delay everyone -- @sivachandran @lgierth @Gaboose and more. I am going to collect the options here and make a decision in coming weeks.
### Proposals so far

So far, the proposals are:
#### Proposal 1: `/dns/<domain>/<proto>`

``` sh
# format
/dns/<domain>/<proto> 

# example
/dns/example.com/ip4  --resolves-to-->  /ip4/1.2.3.4
```
#### Proposal 2: `/dns/<domain>/<record-type>`

``` sh
# format
/dns/<domain>/<record-type> 

# possibilities / examples 
/dns/example.com/A     --resolves-to-->  /ip4/1.2.3.4
/dns/example.com/AAAA  --resolves-to-->  /ip6/1::1
/dns/example.com/CNAME --resolves-to-->  /dns/another.com/*
/dns/example.com/MX    --resolves-to-->  /dns/mail.another.com/* 
/dns/example.com/A     --resolves-to-->  /dns/another.com/A  (through a CNAME)
/dns/example.com/TXT   --resolves-to-->  /ipfs/QmZS2PeM6rtSJXPPSBiqyNRss3M1JpuNAkkQmzEWR7aw1w  (through a dnslink)
```
### Other Questions
- could we support both proposals?
- are there other proposals?
- can we come up with a long list of all the concrete example resolutions we want? (engineer to the use case)
- maybe (for CNAME, MX, etc) we can return a multiaddr that is "[either ip4 or ip6](https://github.com/multiformats/multiaddr/issues/21)" or a "[combination](https://github.com/multiformats/multiaddr/issues/20)"?
- what would just `/dns/example.com` mean? a list or combination? (`1 -> many`)

**Comment by ProgVal** [comment]
Other proposal: have both a modified version of proposal 1 (let's call it 1b) and proposal 2.

*proposal 1b:* `/resolution/name/proto`

`/resolution/name/proto` could be resolved to any resolution protocol, eg. DNS.

For instance, `/resolution/example.com/ip6    -->    /dns/example.com/AAAA    -->    /ip6/1::1`

**Comment by ProgVal** [comment]
Other issue: how to differentiate “IP over DNS” ([it is possible](http://code.kryo.se/iodine/) and IP over address resolved via DNS?

Both seem to be represented as `/dns/example.org/ip/example.com`

**Comment by ProgVal** [comment]
**Proposal 3 (to be combined with either 1 or 2):** Add address nesting to multiaddr.

This would allow more flexibility in the protocols used for resolution

Example:

```
ip4/[/https/127.0.0.1/dns/example.com/aaaa]/tcp/443    -->    ip4/1.2.3.4/tcp/443
     \                                   /
            this is DNS over HTTPS
```

**Comment by jbenet** [comment]
- nesting is an interesting idea we've discussed before without resolution.
There should be a separate issue tracking it.
- but [ ] are unsafe characters. They may be used in addresses themselves
- what is `/resolution/...` ? Looks like you just mean dns.
- If you somehow mean that the DNS namespace is special/obvious and doesn't
need to be namespaced under `/dns/...` I disagree. It's not special or
obvious.
- your ordering of https is backwards, https should come at the end

**Comment by ProgVal** [comment]
> - what is `/resolution/...` ? Looks like you just mean dns.

Any name resolution system. DNS, /etc/hosts, namecoin, ...

> - If you somehow mean that the DNS namespace is special/obvious and doesn't need to be namespaced under `/dns/...` 

I don't

> - your ordering of https is backwards, https should come at the end

No, I meant DNS inside HTTPS

**Comment by ProgVal** [comment]
Oops, I understand my mistake about HTTPS, nevermind

**Comment by lgierth** [comment]
I'll get to writing up a proposal and code in the next 3 weeks.

**Comment by lgierth** [comment]
# /dns in multiaddrs

We had a very productive call about /dns and /tls multiaddrs a while ago, here's the results.
For both /dns and /tls we want to with the simplest options that could possibly work.
These options also must not be in the way of expanding this in the future.

- Comments on proposal 1:
  - It specifies record types in terms of multiaddr protocols (ip4, ip6) which is GOOD.
  - It has 3 segments. This is not a problem in itself, but complicates implementation and adoption,
    since there's *tons of code* that just blindly assumes multiaddr protocols always have 2 segments.
- Comments on proposal 2:
  - Has 3 segments too.
  - Couples multiaddrs to DNS implementation details (record types).
  - Includes unneccessary record types.

## The plan

*Based on proposal 3 which was brought up in the call.*

- Plain and simple: `/dns/example.com`
- Multiaddrs will get `Resolve()` method which returns a list of resolved multiaddrs,
  e.g. `Multiaddr("/dns/example.com/tcp/4001").Resolve()` returns
  `[]string{Multiaddr("/ip4/1.2.3.4/tcp/4001"), Multiaddr("/ip6/1:2:3:4::/tcp/4001")}`.
- Some part within the libp2p stack will decide which of the resolved addresses are usable.
  - Based on which listeners and dialers are available.
  - Based on the Happy Eyeballs algorithm ([RFC 6555](https://tools.ietf.org/html/rfc6555)).
- The domain name should be subject to go-is-domain,
  which should get regex-based check in addition to the check based on the ICANN TLD list.

We'll tag this new multiaddr protocol as `/dns-3` for now, and once it stabilizes promote it to `/dns`.

---

In addition to `/dns`, we could add two more protocols `/dns4` and `/dns6`,
which are explicit about the protocol of the to-be-resolved address, and make
decisions based on listeners/dialers or RFC 6555 unneccessary.

---

Issues down the road:
- Can't currently combine round-robin DNS with /ipfs multiaddrs,
  since these contain the PeerID which is unique per host.
  We could do something certificate-chain-like and have the node's key
  signed by the key corresponding to the given PeerID.

**Comment by diasdavid** [comment]
Linking https://github.com/ipfs/pm/issues/102, which has the notes from that discussion: https://hackmd.io/KbAcFYGYEME4AYC0BjALAMwEyI9YjYAjebVARgHZR5x1VoA2C2IA#

**Comment by lgierth** [comment]
Modification to the plan: we've started doing /dns4 and /dns6 instead of /dns. They yield /ip4 or /ip6 addresses respectively, instead of both /ip4 and /ip6. This helps in unambiguously addressing and endpoint.

We're also not doing experimental protocol names, to avoid the mistake of the various `X-` HTTP headers.

**Comment by kpcyrd** [comment]
A quick question (as it's probably worth defining this), does `/dns` respect `nsswitch`? This way we would get support for `/etc/hosts` and a bunch of other resolution techniques.

**Comment by lgierth** [comment]
That'd be an implementation detail, but most will probably just defer to the system for name resolution. In the browser, it defers to the browser and never actually gets to see an /ip4 address.

Thanks, should write down that implementations SHOULD defer to the system, but MAY come up with their own way of resolving names.

**Comment by Nemo157** [comment]
I haven't looked through the linked discussions yet, but have SRV records been brought up at all, or is this all based off using A/AAAA records only?

**Comment by olizilla** [comment]
Without a `/dns` protocol in multiaddr it's not possible to convert from a URL with a domain name in it to a multiaddr without DNS requests to determine if it's of type dns4 or dns6. In the browser, I'd like to be able to convert `window.location.origin` to a multiaddr like:

```js
Multiaddr.fromUrl(window.location.origin) // e.g https://github.com
// /dns/github.com/tcp/443/https ?
```

**Comment by Stebalien** [comment]
Implementation of `/dns` in go: https://github.com/multiformats/go-multiaddr-dns/pull/17. I did this as we _already_ have to resolve to multiple addresses so this hardly makes the situation any worse. Objections/thoughts?

**Comment by alexander255** [comment]
:+1:

`py-multiaddr` already encodes it like the other DNS types: https://github.com/multiformats/py-multiaddr/blob/master/multiaddr/protocols.py#L130
`py-ipfs-http-client` resolves it as such: https://github.com/ipfs/py-ipfs-api/blob/master/ipfshttpclient/http.py#L168-L206 (Yes, this is my fault, but it's part of the API now. 😉)

OT:

 1. What's the binary encoding for DNS addresses? `py-multiaddr` encodes them as IDNA, but I'm not sure that's interoperable with other implementations?
 2. Could somebody with the required privileges *finally* rename the `py-ipfs-http-client` repo?

**Comment by Stebalien** [comment]
>     What's the binary encoding for DNS addresses? py-multiaddr encodes them as IDNA, but I'm not sure that's interoperable with other implementations?

I think the answer is "none". Could you file a new issue for domain name encoding, that's a question we need to answer.

> Could somebody with the required privileges finally rename the py-ipfs-http-client repo?

Done (please bug me on #ipfs-dev if something like that falls through the cracks).

**Comment by Stebalien** [comment]
Also, it looks like the "dns4 and dns6 only" resolution was just a go thing. JS also supports them.

**Comment by alexander255** [comment]
> > ```
> > What's the binary encoding for DNS addresses? py-multiaddr encodes them as IDNA, but I'm not sure that's interoperable with other implementations?
> > ```
> 
> I think the answer is "none". Could you file a new issue for domain name encoding, that's a question we need to answer.

Will do this.

> 
> > Could somebody with the required privileges finally rename the py-ipfs-http-client repo?
> 
> Done (please bug me on #ipfs-dev if something like that falls through the cracks).

Will remember that in the future. Thanks for finally fixing this!

**Comment by alexander255** [comment]
see #100 for a spec fix

**Comment by Ericson2314** [comment]
> I haven't looked through the linked discussions yet, but have SRV records been brought up at all, or is this all based off using A/AAAA records only?

I too am interested in SRV records. Are records besides A and AAAA decidedly out of scope, or just deemed lower priority and left for the future with the "proposal 3" that was chosen above and since implemented?
