### ISSUE TITLE
NPM, GIT and related

### ISSUE THREAD

**Issue by crackcomm** [multiformats/multiaddr#48]
I would like to use [multiaddr](https://github.com/multiformats/multiaddr) for locating packages like in npm package.json.

```JSON
{
  "dependencies": {
    "http": "/ipfs/QmVv4Wz46JaZJeH5PMV4LGbRiiMKEmszPYY3g6fjGnVXBS",
    "react-fatigue-dev": "/github/tj:react-fatigue-dev",
    "lodash": "/npm/lodash"
  }
}
```

### Github address

I think `github` address is a good idea, it is just a wrapper for the address.
Github address is much simpler because we can use `:` for user and repository separator.

```Shell
/github/tj:react-fatigue-dev --->
  /dns/github.com/git/tj:react-fatigue-dev ---> tj/react-fatigue-dev in fact
```

### Git address

Github address does not solve the problem if we cannot create a valid multiaddr for the repo.

```Shell
/dns/github.com/git/tj/react-fatigue-dev ---> invalid multiaddr?
```

**Comment by whyrusleeping** [comment]
hrm... this is interesting. I very much like the `/git/` idea.

cc @lgierth @Kubuxu @Stebalien for their thoughts

**Comment by Stebalien** [comment]
I am *strongly* against a `/github/` address because that would mean baking something that relies on a proprietary service into a spec. However, I do sympathize with this issue: multiaddrs are verbose.

---

(I may not know enough to speak on the following subject but I'm going to anyways. If I'm wrong about something, please correct me).

As for `/git/`, the problem is that multiaddrs don't do pathing very well. IMO, this is a much bigger problem and needs to be solved once and for all. Maybe introduce a "multipath" spec (multiaddr + path-at-target-address)? Is this already a thing (I'm not entirely up-to-date on the multi* specs and I can't find any information on this)?

For example, we could designate certain protocols as "terminal" protocols and allow arbitrary paths after them: `/dns/github.com/http/tj/react-fatigue-dev`. This would actually allow us to treat IPFS as a multiprotocol (where `ipfs` is a terminal protocol). Alternatively, we could introduce some kind of special character to end a multiprotocol and begin the path portion : `/dns/github.com/http:/tj/react-fatigue-dev`. This would make browser vendors happy...

**Comment by crackcomm** [comment]
Some more random ideas about terminals…

```
/dns/github.com/http@tj/./react-fatigue-dev
/dns/github.com/http/@/tj/./react-fatigue-dev
/dns/github.com/http/:/tj/./react-fatigue-dev
/dns/github.com/http/-/tj/./react-fatigue-dev
/dns/github.com/http/~/tj/react-fatigue-dev
/dns/github.com/http/path/tj/react-fatigue-dev
```

**Comment by crackcomm** [comment]
@Stebalien `ipfs` being a terminal protocol would mean the same for `ipns` because `/ipns/<path>` → `/ipfs/<path>` multiaddrs, and it cannot be.

**Comment by crackcomm** [comment]
There is also possibility of nesting, I don't like that too much but it gives more power.

```
/dns/superapi.com/http/path/(api/endpoint/v1)/protocol/…
```

**Comment by Stebalien** [comment]
> ipfs being a terminal protocol would mean the same for ipns because /ipns/<path> → /ipfs/<path> multiaddrs and it cannot be.

Can you give an example about how this wouldn't work?

> `/ipfs/…/…` is usually not a multiaddr anyway.

Not currently. But then again, what you want isn't really a multiaddr either: it's a multiaddr + path. My point was that we could unify multiaddrs and paths into a some form of multipath spec (with a better name)...

> There is also possibility of nesting...

Can you give a use-case? I considered this but couldn't think of a case where one would switch to a free-form path and then *back* to a multiaddr.

---

To give some context, I'd like to see the multiaddr space mounted as the root filesystem in some future operating system. To access a file, you'd path through the multiaddr space and then continue pathing through the endpoint.

```
/
├── dns/
│  └── github.com/
├── ip/
│  └── 8.8.8.8/
│     ├── tcp/
│     │  └── 53/
│     └── udp/
│        └── 53/
├── ip4/
│  └── 8.8.8.8/
│     ├── tcp/
│     │  └── 53/
│     └── udp/
│        └── 53/
├── ip6/
├── ipfs/
├── ipns/
│  └── QmTLqyWzUWQHzKDK9vsCq141saESJ1uxEJs2EJCcX1THNV/
│     ├── system/
│     │  └── configs_go_here
│     └── user/
│        └── my_personal_space
├── p2p/
└── unix -> ipns/QmTLqyWzUWQHzKDK9vsCq141saESJ1uxEJs2EJCcX1THNV
```

**Comment by crackcomm** [comment]
> Can you give an example about how this wouldn't work?

Actually it would.

> Not currently. But then again, what you want isn't really a multiaddr either: it's a multiaddr + path. My point was that we could unify multiaddrs and paths into a some form of multipath spec (with a better name)...

But as you can see it wouldn't be a multiaddr.

We cannot say what a multiaddr is and is not because it is not specified. Implementations (eq. [js-multiaddr](https://github.com/multiformats/js-multiaddr)) do not respect this kind of a multiaddr.

> Can you give a use-case? I considered this but couldn't think of a case where one would switch to a free-form path and then back to a multiaddr.

Take for example an endpoint which is proxied by a specified http2 route.

```
/dns/superapi.com/http/path/[api/endpoint/v1]/protocol/…
```

It's kinda crazy but it is an example use-case.

I do not like the idea of nesting too.

**Comment by Stebalien** [comment]
> Take for example an endpoint which is proxied by a specified http2 route.
>
>     /dns/superapi.com/http/path/[api/endpoint/v1]/protocol/…

I see. To give a more concrete example: `/dns/mysite.com/wss/path/[some/wss/endpoint]/chat-proto/chat-room`.

One kind of awful way to do this would be to define `[` and `]` as "enter path" and "exit path" protocols:

```
/dns/mysite.com/wss/[/some/wss/endpoint/]/chat-proto/chat-room
```

An alternative is to either URL encode the slashes or do what systemd does and replace `/` with `-`:

```
/dns/mysite.com/wss/path/some-wss-endpoint/chat-proto/chat-room
```

Unfortunately, systemd replaces all instances of `-` with `\x2d`.

**Comment by Nemo157** [comment]
It seems like a `/git/` protocol should come at the end, since it's layering another protocol on top of an existing protocol (http/ssh). Using the "kind of awful" path encoding, that could give the following multiaddrs for this repository (assuming the existence of an `/ssh/` protocol that works with an optional `/path/` protocol):

```
/dns/github.com/http/[/multiformats/multiaddr/]/git
/dns/github.com/ssh/path/[/multiformats/multiaddr/]/git
```

And I would hope there was a way to extend that with a reference and an internal path

```
/dns/github.com/http/[/multiformats/multiaddr/]/git/refs/[/heads/master/]/path/[/README.md/]/
```

But, is this getting far too application specific for `multiaddr`?

**Comment by crackcomm** [comment]
@Nemo157 I agree, it may seem functional at first sight but is it actually worth it?

It would hurt simple beauty of `multiaddr` **design**.
