### ISSUE TITLE
/ws with paths not supported?

### ISSUE THREAD

**Issue by parkan** [multiformats/multiaddr#67]
It appears that specifying a path with websockets is not supported. This isn't explicit (the /protocols dir from the README is missing) but at all the examples I can find use a `/ip4/x.x.x.x/tcp/XXXX/ws` type format and the [test file for go-ipfs](https://github.com/multiformats/go-multiaddr/blob/92dbd0db4f2f05f40ce44df69ab89e3e2f3fda40/multiaddr_test.go#L20) specifies `/ws/foo` as an invalid test case.

e.g. the javascript library [ws](https://www.npmjs.com/package/ws) does allow you to specify a path:

```js
new WebSocket('ws://www.host.com/path')
```

while this isn't meaningful on the websockets side, it can be useful when e.g. using nginx to upgrade a connection to a particular path. Was this a conscious decision?

**Comment by Stebalien** [comment]
This is probably due to the fact that multiaddrs suck at "path" arguments. They can sort of handle them as long as they appear at the end of the address unfortunately, we'd want to support `/ip4/x.x.x.x/tcp/XXXX/ws/a/b/c/ipfs/QmID`. Really, we'd need to write this as `/.../ws/[/a/b/c/d]/ipfs/QmID` (or some escaping mechanism). However, any time anyone brings up a proposal to deal with internal paths paths (e.g., multiaddrs as arguments to multiaddr protocols) the conversation starts at "the syntax is to complicated" and ends with "we don't really *need* them, do we?".

So, no, we don't currently support paths.

**Comment by parkan** [comment]
got it, the current workaround is to use alternate ports with no path component -- works fine for us because we have complete firewall control, but that's not always the case
