### ISSUE TITLE
python implementation

### ISSUE THREAD

**Issue by amstocker** [multiformats/multiaddr#7]
I am slowly but surely moving IPFS in the Python direction :)

I'm currently working on an [implementation of multiaddr in python](https://github.com/amstocker/python-multiaddr) and I had a few questions.
- What is the point of the binary format in terms of communicating with the IFPS api?  Or is it only used internally?
- In the binary format, is every part encoded as an unsigned varint?  Or just the protocol codes and IPFS hashes?

**Comment by jbenet** [comment]
- the binary format is to be able to store + transmit compact addresses. (say 5 bytes compact vs 20 bytes string `/ip4/100.100.100.100`)
- every part is encoded according to that addr's encoding. each multiaddr component has its own way of encoding and decoding. most are straight forward, like tcp ports go from a `uint8 + uint16` to `"/tcp/<int>"`, but ipv4 goes from a `uint8 + uint32` to `"/ip4/<ip addr dot notation>"`. (does this make sense?)

**Comment by jbenet** [comment]
this is great btw. pr when you want your impl added to this repo

**Comment by fredthomsen** [comment]
Looks like this conflicts with the python implementation specified in the README.  Is the version tagged in the README the authoritative one now? Just want to be sure I just contributed to the right place.

**Comment by RichardLitt** [comment]
Good question. @jbenet?

**Comment by diasdavid** [comment]
Apparently, there are two implementations:

- https://github.com/sbuss/py-multiaddr
- https://github.com/amstocker/python-multiaddr

There is no authoritative one for now, both can coexist and evolve and their captains maintain it :) It would be great to converge efforts though, less time spent. @sbuss? @amstocker?

**Comment by amstocker** [comment]
@diasdavid I started this a long time ago the implementation by @sbuss appears to be much more thorough and recent than mine, so I say that one should be the authoritative one :)

**Comment by sbuss** [comment]
I haven't worked on py-multiaddr in a while, but it was well tested and fully compatible with what existed when I wrote it. I'd be happy to collaborate.

**Comment by diasdavid** [comment]
Thank you for jumping right into this issue. Here is what I think it is the best approach to move forward:

- [x] create a Python Team on multiformats and invite you both: https://github.com/orgs/multiformats/teams/python-team
- [ ] move/fork one of your implementations to this org. Seems that the best bet would be @sbuss.
- [ ] copy the tests from @amstocker to the py-multiaddr(previously sbuss/py-multiaddr) available in this repo.
- [ ] Add to the acknowledgements section a pointer to both of the original repos, with proper appreciation

This way, we will have one py-multiaddr implementation that will be easy to find and since you both are now on the python team, you can contribute to the same codebase on that repo.

Sounds good?

**Comment by RichardLitt** [comment]
Also:
- [ ] Add the repos to the main list of multiformats on multiformats/multiformats
- [ ] Conform READMEs to our standard (I can help with this)

**Comment by raulk** [comment]
@zixuanzh and his team are working on [py-libp2p](https://github.com/zixuanzh/py-libp2p/).

@zixuanzh – were you able to evaluate @sbuss's implementation of [py-multiaddr](https://github.com/sbuss/py-multiaddr)? Might be somewhat outdated, but you guys could take up the baton, and bring it up to speed!

@sbuss – would you be happy transferring this repo to the libp2p organisation, so that your work is leveraged and continues developing inside the community? Thanks!

**Comment by zixuanzh** [comment]
@raulk yes, we would love to take it up. We talked about building on top of that repo before, perfect.

**Comment by sbuss** [comment]
> @sbuss – would you be happy transferring this repo to the libp2p organisation, so that your work is leveraged and continues developing inside the community? Thanks!

closing the loop -- I have transferred the repo to the multiformats org
